name: Initialize GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true # This helps enable GitHub Pages if not already enabled

      - name: Create minimal page
        run: |
          mkdir -p public
          echo "<html><body><h1>GitHub Pages Initialization</h1><p>Please use the main workflow for deployment.</p></body></html>" > public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
